### Ноутбук, в котором генерируются фичи с использованием OpenFE

In [ ]:
import pandas as pd

from ml_pipeline.classification.config import classification_config as config
from ml_pipeline.base.utils import set_seed

In [2]:
set_seed(config.general.seed)

In [3]:
full_df = pd.read_csv(config.paths.train, index_col="PassengerId")
full_test_df = pd.read_csv(config.paths.test, index_col="PassengerId")
full_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Логистическая регрессия - просто как модель, из параметров которой можно взять список препроцессоров

По сути тут используется конфиг пайплайна без самого пайплайна

In [4]:
config_logreg = config.copy()

model_name = "logistic_regression"

config_logreg.experiment.to_train = [
    {
        "model": model_name
    }
]

config_logreg.split.cv = False

In [5]:
from ml_pipeline.utils import build_transformers, apply_transformers

model_config = config_logreg.models.get(model_name)

target = config_logreg.data.target_col

y = full_df[target].values
X_train_raw = full_df.drop(columns=[target])

preprocess_transformers = build_transformers(model_config, config_logreg)

X_train = apply_transformers(preprocess_transformers, X_train_raw, fit=True)
X_test = apply_transformers(preprocess_transformers, full_test_df, fit=False)

In [7]:
from openfe import OpenFE, transform

ofe = OpenFE()

features = ofe.fit(data=X_train, label=y, n_jobs=4)

The number of candidate features is 1449
Start stage I selection.

100%|██████████| 16/16 [00:04<00:00,  3.26it/s]

1147 same features have been deleted.
Meet early-stopping in successive feature-wise halving.

100%|██████████| 16/16 [00:03<00:00,  4.95it/s]

The number of remaining candidate features is 301
Start stage II selection.

100%|██████████| 16/16 [00:02<00:00,  6.31it/s]

Finish data processing.

In [ ]:
ofe_train_x, ofe_test_x = transform(X_train, X_test, features, n_jobs=4) # transform the train and test data according to generated features.

Поменять название индекса и влить таргет в один датафрейм

In [ ]:
ofe_train_x.index.name = 'PassengerId'
ofe_train_x['Survived'] = y
ofe_train_x

C:\Users\az\AppData\Local\Temp\ipykernel_21696\4170147582.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x['Survived'] = y

             Pclass  Sex  SibSp  ...  autoFE_f_299  autoFE_f_300  Survived
PassengerId                      ...
1                 3    0      1  ...           3.0      0.420000         0
2                 1    1      1  ...           2.0      0.883721         1
3                 3    1      0  ...           4.0      0.420000         1
4                 1    1      1  ...           2.0      0.383721         1
5                 3    0      0  ...           3.0      0.383721         0
...             ...  ...    ...  ...           ...           ...       ...
887               2    0      0  ...           2.0      0.420000         0
888               1    1      0  ...           2.0      0.420000         1
889               3    1      1  ...           4.0      0.420000         0
890               1    0      0  ...           1.0      0.920000         1
891               3    0      0  ...           3.0      0.420000         0

[891 rows x 314 columns]

In [ ]:
ofe_test_x

             Pclass  Sex  SibSp  ...  autoFE_f_298  autoFE_f_299  autoFE_f_300
PassengerId                      ...
892               3    0      0  ...           3.0           3.0      0.383721
893               3    1      1  ...           3.0           4.0      0.383721
894               2    0      0  ...           4.0           2.0      0.349057
895               3    0      0  ...           2.0           3.0      0.420000
896               3    1      1  ...           2.0           4.0      0.420000
...             ...  ...    ...  ...           ...           ...           ...
1305              3    0      0  ...           3.0           3.0      0.383721
1306              1    1      0  ...           3.0           2.0      0.883721
1307              3    0      0  ...           3.0           3.0      0.383721
1308              3    0      0  ...           3.0           3.0      0.383721
1309              3    0      1  ...           2.0           3.0      0.896429

[418 rows x 313 columns]

Сохранить в csv

In [ ]:
ofe_train_x.to_csv(f"data/train_openfe.csv", index=True)

In [ ]:
ofe_test_x.to_csv(f"data/test_openfe.csv", index=True)