### Titanic First Iteration (04 May)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [83]:
train_df =  pd.read_csv('data/train.csv', index_col='PassengerId')
train_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [84]:
train_df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [85]:
cat_cols = ['Sex', 'Pclass', 'SibSp', 'Embarked', 'Parch']
[print(train_df[x].value_counts(), '\n') for x in cat_cols]

Sex
male      577
female    314
Name: count, dtype: int64

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64

[None, None, None, None, None]

In [86]:
# TODO extract letter from cabin
train_df.Cabin.value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F33            3
E101           3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [87]:
train_df.loc[:, ~train_df.columns.isin(cat_cols)]

,Survived,Name,Age,Ticket,Fare,Cabin
PassengerId,,,,,,
1,0,"Braund, Mr. Owen Harris",22.0,A/5 21171,7.2500,NaN
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,71.2833,C85
3,1,"Heikkinen, Miss. Laina",26.0,STON/O2. 3101282,7.9250,NaN
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,53.1000,C123
5,0,"Allen, Mr. William Henry",35.0,373450,8.0500,NaN
...,...,...,...,...,...,...
887,0,"Montvila, Rev. Juozas",27.0,211536,13.0000,NaN
888,1,"Graham, Miss. Margaret Edith",19.0,112053,30.0000,B42
889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,W./C. 6607,23.4500,NaN
890,1,"Behr, Mr. Karl Howell",26.0,111369,30.0000,C148
891,0,"Dooley, Mr. Patrick",32.0,370376,7.7500,NaN

In [88]:
numeric_cols = ['Age', 'Fare']
train_df[numeric_cols]

              Age     Fare
PassengerId
1            22.0   7.2500
2            38.0  71.2833
3            26.0   7.9250
4            35.0  53.1000
5            35.0   8.0500
...           ...      ...
887          27.0  13.0000
888          19.0  30.0000
889           NaN  23.4500
890          26.0  30.0000
891          32.0   7.7500

[891 rows x 2 columns]

In [92]:
first_iter_df = train_df[[*cat_cols, *numeric_cols, 'Survived']]
first_iter_df

                Sex  Pclass  SibSp Embarked  Parch   Age     Fare  Survived
PassengerId
1              male       3      1        S      0  22.0   7.2500         0
2            female       1      1        C      0  38.0  71.2833         1
3            female       3      0        S      0  26.0   7.9250         1
4            female       1      1        S      0  35.0  53.1000         1
5              male       3      0        S      0  35.0   8.0500         0
...             ...     ...    ...      ...    ...   ...      ...       ...
887            male       2      0        S      0  27.0  13.0000         0
888          female       1      0        S      0  19.0  30.0000         1
889          female       3      1        S      2   NaN  23.4500         0
890            male       1      0        C      0  26.0  30.0000         1
891            male       3      0        Q      0  32.0   7.7500         0

[891 rows x 8 columns]

#### Feature Engineering

##### First N/A approach: drop N/A

In [93]:
first_iter_df.Age.notna().sum()

np.int64(714)

In [94]:
first_iter_df = first_iter_df.dropna()
first_iter_df

                Sex  Pclass  SibSp Embarked  Parch   Age     Fare  Survived
PassengerId
1              male       3      1        S      0  22.0   7.2500         0
2            female       1      1        C      0  38.0  71.2833         1
3            female       3      0        S      0  26.0   7.9250         1
4            female       1      1        S      0  35.0  53.1000         1
5              male       3      0        S      0  35.0   8.0500         0
...             ...     ...    ...      ...    ...   ...      ...       ...
886          female       3      0        Q      5  39.0  29.1250         0
887            male       2      0        S      0  27.0  13.0000         0
888          female       1      0        S      0  19.0  30.0000         1
890            male       1      0        C      0  26.0  30.0000         1
891            male       3      0        Q      0  32.0   7.7500         0

[712 rows x 8 columns]

##### Sex feature

In [95]:
if 'Sex' in first_iter_df.columns:
    first_iter_df['is_female'] = (first_iter_df.Sex == 'female').astype('int')
    first_iter_df = first_iter_df.drop(columns=['Sex'])
first_iter_df

             Pclass  SibSp Embarked  Parch   Age     Fare  Survived  is_female
PassengerId
1                 3      1        S      0  22.0   7.2500         0          0
2                 1      1        C      0  38.0  71.2833         1          1
3                 3      0        S      0  26.0   7.9250         1          1
4                 1      1        S      0  35.0  53.1000         1          1
5                 3      0        S      0  35.0   8.0500         0          0
...             ...    ...      ...    ...   ...      ...       ...        ...
886               3      0        Q      5  39.0  29.1250         0          1
887               2      0        S      0  27.0  13.0000         0          0
888               1      0        S      0  19.0  30.0000         1          1
890               1      0        C      0  26.0  30.0000         1          0
891               3      0        Q      0  32.0   7.7500         0          0

[712 rows x 8 columns]

##### Scaling

In [96]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()

first_iter_df[numeric_cols] = scaler.fit_transform(first_iter_df[numeric_cols])
first_iter_df

,Pclass,SibSp,Embarked,Parch,Age,Fare,Survived,is_female
PassengerId,,,,,,,,
1,3,1,S,0,-0.527669,-0.516380,0,0
2,1,1,C,0,0.577094,0.694046,1,1
3,3,0,S,0,-0.251478,-0.503620,1,1
4,1,1,S,0,0.369951,0.350326,1,1
5,3,0,S,0,0.369951,-0.501257,0,0
...,...,...,...,...,...,...,...,...
886,3,0,Q,5,0.646142,-0.102875,0,1
887,2,0,S,0,-0.182430,-0.407687,0,0
888,1,0,S,0,-0.734812,-0.086335,1,1
890,1,0,C,0,-0.251478,-0.086335,1,0
891,3,0,Q,0,0.162808,-0.506928,0,0

In [97]:
cols_to_minmax_scale = cat_cols[:]
cols_to_minmax_scale.remove('Sex')
cols_to_minmax_scale.remove('Embarked')
cols_to_minmax_scale

['Pclass', 'SibSp', 'Parch']

In [98]:
mm_scaler = MinMaxScaler()

first_iter_df[cols_to_minmax_scale] = mm_scaler.fit_transform(first_iter_df[cols_to_minmax_scale])
first_iter_df

,Pclass,SibSp,Embarked,Parch,Age,Fare,Survived,is_female
PassengerId,,,,,,,,
1,1.0,0.2,S,0.000000,-0.527669,-0.516380,0,0
2,0.0,0.2,C,0.000000,0.577094,0.694046,1,1
3,1.0,0.0,S,0.000000,-0.251478,-0.503620,1,1
4,0.0,0.2,S,0.000000,0.369951,0.350326,1,1
5,1.0,0.0,S,0.000000,0.369951,-0.501257,0,0
...,...,...,...,...,...,...,...,...
886,1.0,0.0,Q,0.833333,0.646142,-0.102875,0,1
887,0.5,0.0,S,0.000000,-0.182430,-0.407687,0,0
888,0.0,0.0,S,0.000000,-0.734812,-0.086335,1,1
890,0.0,0.0,C,0.000000,-0.251478,-0.086335,1,0
891,1.0,0.0,Q,0.000000,0.162808,-0.506928,0,0

##### Dummies for Embarked

In [99]:
embarked_dummies = pd.get_dummies(first_iter_df.Embarked, dtype=float)
embarked_dummies

               C    Q    S
PassengerId
1            0.0  0.0  1.0
2            1.0  0.0  0.0
3            0.0  0.0  1.0
4            0.0  0.0  1.0
5            0.0  0.0  1.0
...          ...  ...  ...
886          0.0  1.0  0.0
887          0.0  0.0  1.0
888          0.0  0.0  1.0
890          1.0  0.0  0.0
891          0.0  1.0  0.0

[712 rows x 3 columns]

In [100]:
first_iter_df['Embarked_C'] = embarked_dummies['C']
first_iter_df['Embarked_S'] = embarked_dummies['S']

if 'Embarked' in first_iter_df.columns:
    first_iter_df = first_iter_df.drop(columns=['Embarked'])

first_iter_df

,Pclass,SibSp,Parch,Age,Fare,Survived,is_female,Embarked_C,Embarked_S
PassengerId,,,,,,,,,
1,1.0,0.2,0.000000,-0.527669,-0.516380,0,0,0.0,1.0
2,0.0,0.2,0.000000,0.577094,0.694046,1,1,1.0,0.0
3,1.0,0.0,0.000000,-0.251478,-0.503620,1,1,0.0,1.0
4,0.0,0.2,0.000000,0.369951,0.350326,1,1,0.0,1.0
5,1.0,0.0,0.000000,0.369951,-0.501257,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
886,1.0,0.0,0.833333,0.646142,-0.102875,0,1,0.0,0.0
887,0.5,0.0,0.000000,-0.182430,-0.407687,0,0,0.0,1.0
888,0.0,0.0,0.000000,-0.734812,-0.086335,1,1,0.0,1.0
890,0.0,0.0,0.000000,-0.251478,-0.086335,1,0,1.0,0.0
891,1.0,0.0,0.000000,0.162808,-0.506928,0,0,0.0,0.0

In [110]:
y = first_iter_df.Survived
X = first_iter_df.drop(columns=['Survived'])
train_X = X.to_numpy()

In [111]:
train_y = y.to_numpy().reshape(len(y), 1)

## Training

In [121]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

kf = KFold(n_splits=5)

In [122]:
for i, (train_index, test_index) in enumerate(kf.split(train_X)):
    lr = LogisticRegression()

    fitted = lr.fit(train_X[train_index], train_y[train_index])

    y_pred = fitted.predict(train_X[test_index])
    print(mean_squared_error(train_y[test_index], y_pred))

0.21678321678321677
0.1958041958041958
0.23943661971830985
0.2535211267605634
0.176056338028169

x:\DSML\Miniconda\envs\titanic\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
x:\DSML\Miniconda\envs\titanic\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
x:\DSML\Miniconda\envs\titanic\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
x:\DSML\Miniconda\envs\titanic\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
x:\DSML\Miniconda\envs\titanic\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)